
let main () =
	let atomList : Atom.atom list = [
	new Atom.hydrogen "Hydrogen" "H" 1 (* Hydrogen *) ;
	new Atom.helium "Helium" "He" 2 ;
	new Atom.lithium "Lithium" "Li" 3 ;
	new Atom.beryllium "Beryllium" "Be" 4 ;
	new Atom.boron "Boron" "B" 5 ;
	new Atom.carbon "Carbon" "C" 6 (* Carbon *) ;
	new Atom.nitrogen "Nitrogen" "N" 7 ;
	new Atom.oxygen "Oxygen" "O" 8 (* Oxygen *) ;
	new Atom.fluorine "Fluorine" "F" 9 ;
	new Atom.neon "Neon" "Ne" 10 ;
	new Atom.sodium "Sodium" "Na" 11 ;
	new Atom.magnesium "Magnesium" "Mg" 12 ;
	new Atom.aluminium "Aluminum, Aluminium" "Al" 13 ;
	new Atom.silicon "Silicon" "Si" 14 ;
	new Atom.phosphorus "Phosphorus" "P" 15 ;
	new Atom.sulfur "Sulfur" "S" 16 ;
	new Atom.chlorine "Chlorine" "Cl" 17 ;
	new Atom.argon "Argon" "Ar" 18 ;
	new Atom.potassium "Potassium" "K" 19 ;
	new Atom.calcium "Calcium" "Ca" 20 ;
	new Atom.scandium "Scandium" "Sc" 21 ;
	new Atom.titanium "Titanium" "Ti" 22 ;
	new Atom.vanadium "Vanadium" "V" 23 ;
	new Atom.chromium "Chromium" "Cr" 24 ;
	new Atom.manganese "Manganese" "Mn" 25 ;
	new Atom.iron "Iron" "Fe" 26 ;
	new Atom.cobalt "Cobalt" "Co" 27 ;
	new Atom.nickel "Nickel" "Ni" 28 ;
	new Atom.copper "Copper" "Cu" 29 ;
	new Atom.zinc "Zinc" "Zn" 30 ;
	new Atom.gallium "Gallium" "Ga" 31 ;
	new Atom.germanium "Germanium" "Ge" 32 ;
	new Atom.arsenic "Arsenic" "As" 33 ;
	new Atom.selenium "Selenium" "Se" 34 ;
	new Atom.bromine "Bromine" "Br" 35 ;
	new Atom.krypton "Krypton" "Kr" 36 ;
	new Atom.rubidium "Rubidium" "Rb" 37 ;
	new Atom.strontium "Strontium" "Sr" 38 ;
	new Atom.yttrium "Yttrium" "Y" 39 ;
	new Atom.zirconium "Zirconium" "Zr" 40 ;
	new Atom.niobium "Niobium" "Nb" 41 ;
	new Atom.molybdenum "Molybdenum" "Mo" 42 ;
	new Atom.technetium "Technetium" "Tc" 43 ;
	new Atom.ruthenium "Ruthenium" "Ru" 44 ;
	new Atom.rhodium "Rhodium" "Rh" 45 ;
	new Atom.palladium "Palladium" "Pd" 46 ;
	new Atom.silver "Silver" "Ag" 47 ;
	new Atom.cadmium "Cadmium" "Cd" 48 ;
	new Atom.indium "Indium" "In" 49 ;
	new Atom.tin "Tin" "Sn" 50 ;
	new Atom.antimony "Antimony" "Sb" 51 ;
	new Atom.tellurium "Tellurium" "Te" 52 ;
	new Atom.iodine "Iodine" "I" 53 ;
	new Atom.xenon "Xenon" "Xe" 54 ;
	new Atom.cesium "Cesium" "Cs" 55 ;
	new Atom.barium "Barium" "Ba" 56 ;
	new Atom.lanthanum "Lanthanum" "La" 57 ;
	new Atom.cerium "Cerium" "Ce" 58 ;
	new Atom.praseodymium "Praseodymium" "Pr" 59 ;
	new Atom.neodymium "Neodymium" "Nd" 60 ;
	new Atom.promethium "Promethium" "Pm" 61 ;
	new Atom.samarium "Samarium" "Sm" 62 ;
	new Atom.europium "Europium" "Eu" 63 ;
	new Atom.gadolinium "Gadolinium" "Gd" 64 ;
	new Atom.terbium "Terbium" "Tb" 65 ;
	new Atom.dysprosium "Dysprosium" "Dy" 66 ;
	new Atom.holmium "Holmium" "Ho" 67 ;
	new Atom.erbium "Erbium" "Er" 68 ;
	new Atom.thulium "Thulium" "Tm" 69 ;
	new Atom.ytterbium "Ytterbium" "Yb" 70 ;
	new Atom.lutetium "Lutetium" "Lu" 71 ;
	new Atom.hafnium "Hafnium" "Hf" 72 ;
	new Atom.tantalum "Tantalum" "Ta" 73 ;
	new Atom.tungsten "Tungsten" "W" 74 ;
	new Atom.rhenium "Rhenium" "Re" 75 ;
	new Atom.osmium "Osmium" "Os" 76 ;
	new Atom.iridium "Iridium" "Ir" 77 ;
	new Atom.platinum "Platinum" "Pt" 78 ;
	new Atom.gold "Gold" "Au" 79 ;
	new Atom.mercury "Mercury" "Hg" 80 ;
	new Atom.thallium "Thallium" "Tl" 81 ;
	new Atom.lead "Lead" "Pb" 82 ;
	new Atom.bismuth "Bismuth" "Bi" 83 ;
	new Atom.polonium "Polonium" "Po" 84 ;
	new Atom.astatine "Astatine" "At" 85 ;
	new Atom.radon "Radon" "Rn" 86 ;
	new Atom.francium "Francium" "Fr" 87 ;
	new Atom.radium "Radium" "Ra" 88 ;
	new Atom.actinium "Actinium" "Ac" 89 ;
	new Atom.thorium "Thorium" "Th" 90 ;
	new Atom.protactinium "Protactinium" "Pa" 91 ;
	new Atom.uranium "Uranium" "U" 92 ;
	new Atom.neptunium "Neptunium" "Np" 93 ;
	new Atom.plutonium "Plutonium" "Pu" 94 ;
	new Atom.americium "Americium" "Am" 95 ;
	new Atom.curium "Curium" "Cm" 96 ;
	new Atom.berkelium "Berkelium" "Bk" 97 ;
	new Atom.californium "Californium" "Cf" 98 ;
	new Atom.einsteinium "Einsteinium" "Es" 99 ;
	new Atom.fermium "Fermium" "Fm" 100 ;
	new Atom.mendelevium "Mendelevium" "Md" 101 ;
	new Atom.nobelium "Nobelium" "No" 102 ;
	new Atom.lawrencium "Lawrencium" "Lr" 103 ;
	new Atom.rutherfordium "Rutherfordium" "Rf" 104 ;
	new Atom.dubnium "Dubnium" "Db" 105 ;
	new Atom.seaborgium "Seaborgium" "Sg" 106 ;
	new Atom.bohrium "Bohrium" "Bh" 107 ;
	new Atom.hassium "Hassium" "Hs" 108 ;
	new Atom.meitnerium "Meitnerium" "Mt" 109 ;
	new Atom.darmstadtium "Darmstadtium" "Ds" 110 ;
	new Atom.roentgenium "Roentgenium" "Rg" 111 ;
	new Atom.copernicium "Copernicium" "Cn" 112 ;
	new Atom.ununtrium "Ununtrium" "Uut" 113 ;
	new Atom.flerovium "Flerovium" "Fl" 114 ;
	new Atom.ununpentium "Ununpentium" "Uup" 115 ;
	new Atom.livermorium "Livermorium" "Lv" 116 ;
	new Atom.ununseptium "Ununseptium" "Uus" 117 ;
	new Atom.ununoctium "Ununoctium" "Uuo" 118 ;] in
	(* List.iter  *)
	List.iter (fun (a:Atom.atom) -> print_endline (a#to_string)) atomList

let () = ignore @@ main ()